"""add education field to user

Revision ID: 183ca747e88f
Revises: f72e8ba81d5f
Create Date: 2025-07-08 13:23:51.881785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '183ca747e88f'
down_revision = 'f72e8ba81d5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('education', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('education')

    # ### end Alembic commands ###
