"""Add category, tags, visibility, likes_count, views_count to Post

Revision ID: 5501d4c2adf1
Revises: 86bdecd44fa1
Create Date: 2025-07-09 16:05:17.692845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5501d4c2adf1'
down_revision = '86bdecd44fa1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('visibility', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('tags', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('likes_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('views_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('views_count')
        batch_op.drop_column('likes_count')
        batch_op.drop_column('tags')
        batch_op.drop_column('visibility')
        batch_op.drop_column('category')

    # ### end Alembic commands ###
