"""Update post model fields

Revision ID: 86bdecd44fa1
Revises: 183ca747e88f
Create Date: 2025-07-09 10:15:11.024958

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '86bdecd44fa1'
down_revision = '183ca747e88f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('media_url', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('image')
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('image', mysql.VARCHAR(length=256), nullable=True))
        batch_op.drop_column('created_at')
        batch_op.drop_column('media_url')

    # ### end Alembic commands ###
